export const CHANGE_LOADING = "CHANGE_LOADING";
export const CHANGE_INDEX = "CHANGE_INDEX";
export const CHANGE_SCORE = "CHANGE_SCORE";
export const CHANGE_CITY_TO_FIND = "CHANGE_CITY_TO_FIND";
export const CHANGE_CITY_PLACED = "CHANGE_CITY_PLACED";
export const RESET_REDUX = "RESET_REDUX";
export const CHANGE_CORRECT = "CHANGE_CORRECT";
